# in order to perform sensitivity analysis, these parameters must be changed individually in InputData
# Example: In InputData change the value of ACUPUNCTURE_RR to SA.ACUPUNCTURE_RR_LOW

# probabilities
ACUPUNCTURE_RR_LOW = (1-0.7)
ACUPUNCTURE_RR_HIGH = (1-0.6)

CRANBERRY_RR_LOW = (1-0.8)
CRANBERRY_RR_HIGH = (1-0.4)

DAILY_ANTIBIOTIC_RR_LOW = (1-1)
DAILY_ANTIBIOTIC_RR_HIGH = (1-0.4)

ESTROGEN_RR_LOW = (1-1)
ESTROGEN_RR_HIGH = (1-0.3)

PROB_PYELO_LOW = 0.00
PROB_PYELO_HIGH = 0.08

PROB_URINALYSIS_LOW = 0.25
PROB_URINALYSIS_HIGH = 1

PROB_UTI_DIAGNOSED_LOW = 0.6
PROB_UTI_DIAGNOSED_HIGH = 0.1

PROB_UTI_CURED_LOW = 0.9
PROB_UTI_CURED_HIGH = 1

PROB_PERSISTANT_INFECTION_LOW = 0.92  # inverse of prob of pylonephritis
PROB_PERSISTANT_INFECTION_HIGH = 1

PROB_MODIFIED_ANTIBIOTICS_LOW = 0
PROB_MODIFIED_ANTIBIOTICS_HIGH = 1

PROB_INPATIENT_LOW = 0 # inverse of prob of outpatient treatment
PROB_INPATIENT_HIGH = 0.5

PROB_STI_OR_VAG_LOW = 0
PROB_STI_OR_VAG_HIGH = 0.5

# costs per day
NO_TREATMENT_COST = 0

ACUPUNCTURE_COST_LOW = 1.37
ACUPUNCTURE_COST_HIGH = 4.60

CRANBERRY_COST_LOW = 0.13
CRANBERRY_COST_HIGH = 2.25

ESTROGEN_COST_LOW = 0.14
ESTROGEN_COST_HIGH = 31.63

DAILY_ANTIBIOTIC_COST_LOW = 1
DAILY_ANTIBIOTIC_COST_HIGH = 4

URINALYSIS_COST_LOW = 10
URINALYSIS_COST_HIGH = 42

CIPRO_COST_LOW = 2
CIPRO_COST_HIGH = 10

MD_VISIT_COST_LOW = 65  # follow up
MD_VISIT_COST_HIGH = 132

MODIFIED_ANTIBIOTIC_COST_LOW = 2 # cipro 500???
MODIFIED_ANTIBIOTIC_COST_HIGH = 11

EXTENDED_TREATMENT_COST_LOW = 15
EXTENDED_TREATMENT_COST_HIGH = 60

INPATIENT_TREATMENT_COST_LOW = 850  # lasts 3 days
INPATIENT_TREATMENT_COST_HIGH = 3600

OUTPATIENT_TREATMENT_COST_LOW = 15
OUTPATIENT_TREATMENT_COST_HIGH = 60

STI_OR_VAGINITIS_COST_LOW = 30.65
STI_OR_VAGINITIS_COST_HIGH = 171.25